### ISSUE TITLE
feature request: show the actual version number of the "latest"

### ISSUE THREAD

**Issue by susurri** [veryl-lang/verylup#45]
`verylup setup` installs the latest release of the veryl which has a version number.
However, `verylup show` shows just "latest" and you cannot not know the actual version number.

**Comment by dalance** [comment]
Looks good!
I added this feature by #46.

```
$ ./verylup show
installed toolchains
--------------------

0.9.0
0.10.0
0.11.0
0.12.0
0.13.0
0.13.1
0.13.2
0.13.3
latest: 0.13.3 (default)
```
